import { inRing, type LngLat } from "./area.ts";
import { TERRITORY } from "./generated/territory.ts";

/**
 * Territory: hand-crafted neighborhoods whose borders run down real streets,
 * plus the Ojai Valley Trail as its own thin strip (the game's main walking
 * artery). Factions will hold these; that logic lives elsewhere.
 *
 * The shapes are generated by tools/map/build_territory.py from
 * tools/map/territory.json: a list of border streets and a seed point per
 * neighborhood. To redraw one, edit that file and rerun the script.
 */
export interface Neighborhood {
  id: string;
  name: string;
  /** One line of flavour, for lore and the map sheet. */
  note: string;
  /** Map tint index, picked so neighbours differ. 4 = the trail. */
  tint: number;
  /** Polygons, each [outer ring, ...holes], [lng, lat]. */
  polygons: LngLat[][][];
}

export const NEIGHBORHOODS: Neighborhood[] = TERRITORY;

export const neighborhoodById = (id: string) => NEIGHBORHOODS.find((n) => n.id === id);

const inPolygon = (p: LngLat, [outer, ...holes]: LngLat[][]) => inRing(p, outer) && !holes.some((h) => inRing(p, h));

/** The neighborhood a point is in, or undefined outside the play area. */
export const neighborhoodOf = (p: LngLat) => NEIGHBORHOODS.find((n) => n.polygons.some((poly) => inPolygon(p, poly)));

/** The play area is exactly the neighborhoods. */
export const inPlayArea = (p: LngLat) => neighborhoodOf(p) !== undefined;

/** A point to hang a label on: the centre of the largest polygon's box. */
export function labelPoint(n: Neighborhood): LngLat {
  const box = (ring: LngLat[]) => {
    const xs = ring.map((p) => p[0]);
    const ys = ring.map((p) => p[1]);
    return [Math.min(...xs), Math.min(...ys), Math.max(...xs), Math.max(...ys)];
  };
  const biggest = n.polygons
    .map((poly) => ({ poly, b: box(poly[0]) }))
    .sort((a, b) => (b.b[2] - b.b[0]) * (b.b[3] - b.b[1]) - (a.b[2] - a.b[0]) * (a.b[3] - a.b[1]))[0];
  const c: LngLat = [(biggest.b[0] + biggest.b[2]) / 2, (biggest.b[1] + biggest.b[3]) / 2];
  if (inPolygon(c, biggest.poly)) return c;
  // Concave shape: fall back to the vertex average, then any vertex.
  const ring = biggest.poly[0];
  const avg: LngLat = [ring.reduce((s, p) => s + p[0], 0) / ring.length, ring.reduce((s, p) => s + p[1], 0) / ring.length];
  return inPolygon(avg, biggest.poly) ? avg : ring[0];
}

/** Neighborhoods as a GeoJSON FeatureCollection (for the map, PostGIS, etc.). */
export function neighborhoodsGeoJSON() {
  return {
    type: "FeatureCollection" as const,
    features: NEIGHBORHOODS.map((n) => ({
      type: "Feature" as const,
      id: n.id,
      properties: { id: n.id, name: n.name, tint: n.tint },
      geometry: { type: "MultiPolygon" as const, coordinates: n.polygons },
    })),
  };
}
