import { distanceM, type LngLat } from "./area.ts";
import { GENERATED_SPOTS } from "./generated/territory.ts";

/**
 * Pokémon Go's shape: plain **spots** (its PokéStops) everywhere, and a few
 * **event spots** (its gyms) where timed events and bosses happen.
 *
 * SPOTS below are hand-placed. The rest are generated by
 * tools/map/build_territory.py so a walker is never far from one: public
 * landmarks from the open data, a marker every 200 m along the trail, and
 * street corners filling any gap wider than ~140 m.
 *
 * A spot has no fixed type. What you find there is rolled per player and
 * refreshes every REFRESH_MIN: usually a fight, sometimes a rest, an elite, a
 * shop or a ? event. A spot can lean toward some finds (Krotona toward rest,
 * the Arcade toward shop).
 */
export type Find = "fight" | "elite" | "rest" | "shop" | "mystery";
export type SpotKind = "spot" | "event";

export interface Spot {
  id: string;
  /** Real-world name, for us. Players may see `gameName` instead. */
  name: string;
  /** In-game name when the real one can't be used (real businesses). */
  gameName?: string;
  kind: SpotKind;
  /** Where the spot sits: a public, legal place to stand. */
  at: LngLat;
  /** How close a player must be to play the spot, in metres. */
  radiusM: number;
  /** Multipliers on BASE_ODDS, e.g. { rest: 3 }. */
  leans?: Partial<Record<Find, number>>;
  note: string;
  /** Unchecked facts, to confirm on the ground before launch. */
  verify?: string;
}

/** Relative odds of each find at a plain spot. Tune with the lab. */
export const BASE_ODDS: Record<Find, number> = { fight: 60, rest: 12, elite: 10, shop: 8, mystery: 10 };

/** How often a spot rerolls what you find there, in minutes. */
export const REFRESH_MIN = 20;

// Coordinates are from Overture Maps places and road/trail geometry (see
// tools/map), nudged onto the public side of the property where noted.
export const HAND_SPOTS: Spot[] = [
  // ─── Event spots (gyms): timed events and bosses happen here ──────────────
  {
    id: "shelf-road",
    name: "Shelf Road trailhead (Signal St)",
    kind: "event",
    at: [-119.24586, 34.46221],
    radiusM: 60,
    leans: { elite: 2 },
    note: "The Pink Moment trail. West end, at the top of Signal St, off the roadway.",
  },
  {
    id: "meditation-mount",
    name: "Meditation Mount",
    kind: "event",
    at: [-119.16569, 34.45084],
    radiusM: 80,
    leans: { rest: 3 },
    note: "Public meditation garden with a Pink Moment view, up Reeves Rd east of town.",
    verify: "Hours.",
  },
  {
    id: "sunday-market",
    name: "Farmers market lot (behind the Arcade)",
    kind: "event",
    at: [-119.24439, 34.4485],
    radiusM: 60,
    leans: { shop: 3 },
    note: "Ojai Certified Farmers Market, 300 E Matilija St, Sundays.",
    verify: "Hours.",
  },
  {
    id: "ousd-grounds",
    name: "Old school district grounds (414 E Ojai Ave)",
    kind: "event",
    at: [-119.2428, 34.4489],
    radiusM: 60,
    leans: { shop: 2, mystery: 2 },
    note: "The Thursday People's Market, 3 to 7 PM. Former Ojai Unified grounds, no longer an active school (Sam).",
  },
  {
    id: "libbey-park",
    name: "Libbey Park & Bowl",
    kind: "event",
    at: [-119.24533, 34.44707],
    radiusM: 70,
    note: "Central, walkable, busy. Festivals and town-wide raids. Edward Libbey is a lore figure.",
  },
  {
    id: "oak-grove",
    name: "The Oak Grove (Besant Rd)",
    kind: "event",
    at: [-119.27765, 34.44318],
    radiusM: 50,
    leans: { mystery: 3 },
    note: "Where Krishnamurti gave his talks. On Besant Rd by the Krishnamurti Foundation, outside the school campus.",
    verify: "Oak Grove School is next door; confirm the spot is public and off campus.",
  },
  {
    id: "krotona",
    name: "Krotona Institute of Theosophy",
    kind: "event",
    at: [-119.26973, 34.4376],
    radiusM: 50,
    leans: { rest: 3, mystery: 2 },
    note: "Theosophical HQ since 1924. At the public library/bookshop entrance, not the grounds.",
    verify: "Public access and hours.",
  },

  // ─── Spots (stops): walk by, see what's there ─────────────────────────────
  {
    id: "arcade",
    name: "The Ojai Arcade",
    kind: "spot",
    at: [-119.24461, 34.44811],
    radiusM: 40,
    leans: { shop: 3 },
    note: "Libbey's Mission Revival arcade: the company-town shop.",
  },
  {
    id: "post-office-tower",
    name: "Post Office Tower",
    kind: "spot",
    at: [-119.24577, 34.44753],
    radiusM: 35,
    leans: { elite: 2 },
    note: "Downtown landmark on the Arcade.",
  },
  {
    id: "playhouse",
    name: "Ojai Playhouse",
    kind: "spot",
    at: [-119.24614, 34.44764],
    radiusM: 30,
    leans: { mystery: 2 },
    note: "Old cinema.",
    verify: "Real business: parody-name it.",
  },
  {
    id: "valley-museum",
    name: "Ojai Valley Museum",
    kind: "spot",
    at: [-119.2479, 34.44781],
    radiusM: 40,
    leans: { mystery: 3 },
    note: "Local history; lore drops.",
  },
  {
    id: "barts-books",
    name: "Bart's Books",
    kind: "spot",
    at: [-119.24985, 34.4486],
    radiusM: 40,
    leans: { mystery: 2, shop: 2 },
    note: "Outdoor bookshop with honor-system shelves.",
    verify: "Real business: needs a parody name or their OK.",
  },
  {
    id: "arbolada-gate",
    name: "Arbolada gate (Foothill Rd at Ojai Ave)",
    kind: "spot",
    at: [-119.2517, 34.4476],
    radiusM: 40,
    leans: { elite: 2 },
    note: "Where Foothill Rd leaves Ojai Ave for the oaks. The Oak Grove Mom's home turf.",
  },
  {
    id: "sarzotti-park",
    name: "Sarzotti Park",
    kind: "spot",
    at: [-119.23615, 34.45175],
    radiusM: 70,
    note: "Public park and rec center north-east of downtown.",
  },
  {
    id: "daly-ranch",
    name: "Daly Ranch Park",
    kind: "spot",
    at: [-119.24025, 34.46047],
    radiusM: 70,
    note: "Open space below the bluffs, on the way to Shelf Road.",
    verify: "Public access point.",
  },
  {
    id: "soule-park",
    name: "Soule Park",
    kind: "spot",
    at: [-119.22677, 34.44204],
    radiusM: 90,
    note: "Big county park at the east end.",
  },
  {
    id: "trail-downtown",
    name: "Ojai Valley Trail at Fox St",
    kind: "spot",
    at: [-119.24127, 34.44523],
    radiusM: 50,
    note: "Downtown end of the trail. Morning trail rush happens along here.",
  },
  {
    id: "demo-garden",
    name: "Community Demonstration Garden",
    kind: "spot",
    at: [-119.24703, 34.44356],
    radiusM: 40,
    leans: { rest: 3 },
    note: "Community garden just south of Libbey Park.",
    verify: "Public access.",
  },
  {
    id: "rotary-park",
    name: "Rotary Community Park",
    kind: "spot",
    at: [-119.26026, 34.44146],
    radiusM: 60,
    note: "Park and playground off Maricopa Hwy.",
  },
  {
    id: "trail-mira-monte",
    name: "Ojai Valley Trail at Mira Monte",
    kind: "spot",
    at: [-119.27472, 34.43243],
    radiusM: 50,
    note: "Where the trail passes below Meiners Oaks.",
  },
  {
    id: "el-roblar",
    name: "El Roblar Dr (Meiners Oaks)",
    kind: "spot",
    at: [-119.2776, 34.4488],
    radiusM: 80,
    leans: { shop: 3 },
    note: "The other town's main street: cafés, the nursery, Farmer and the Cook.",
  },
  {
    id: "meiners-oaks-park",
    name: "Meiners Oaks Park",
    kind: "spot",
    at: [-119.2719, 34.4481],
    radiusM: 50,
    note: "Neighborhood park off El Roblar.",
  },
];

const GENERATED_NOTE: Record<string, string> = {
  trail: "A marker on the Ojai Valley Trail.",
  corner: "A street corner.",
};

export const SPOTS: Spot[] = [
  ...HAND_SPOTS,
  ...GENERATED_SPOTS.map((g): Spot => ({
    id: g.id,
    name: g.name,
    kind: "spot",
    at: g.at,
    radiusM: 35,
    note: GENERATED_NOTE[g.source] ?? `From the open map data (${g.source.replaceAll("_", " ")}).`,
    ...(g.verify ? { verify: g.verify } : {}),
  })),
];

export const spotById = (id: string) => SPOTS.find((s) => s.id === id);

/** Spots whose play radius the point is inside, nearest first. */
export function spotsInRange(p: LngLat): Spot[] {
  return SPOTS.map((s) => ({ s, d: distanceM(p, s.at) }))
    .filter(({ s, d }) => d <= s.radiusM)
    .sort((a, b) => a.d - b.d)
    .map(({ s }) => s);
}

/** The odds at one spot: BASE_ODDS times its leans, as fractions summing to 1. */
export function spotOdds(spot: Spot): Record<Find, number> {
  const raw = Object.fromEntries(
    (Object.keys(BASE_ODDS) as Find[]).map((f) => [f, BASE_ODDS[f] * (spot.leans?.[f] ?? 1)]),
  ) as Record<Find, number>;
  const total = Object.values(raw).reduce((a, b) => a + b, 0);
  for (const f of Object.keys(raw) as Find[]) raw[f] /= total;
  return raw;
}

/** FNV-1a → [0, 1). */
function hash01(s: string): number {
  let h = 0x811c9dc5;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return (h >>> 0) / 2 ** 32;
}

/**
 * What a player finds at a spot right now. Deterministic from (spot, player,
 * time slot), so the server can check it and the same player sees the same
 * thing until the slot turns over.
 */
export function findAt(spot: Spot, playerId: string, when: Date): Find {
  const slot = Math.floor(when.getTime() / (REFRESH_MIN * 6e4));
  let r = hash01(`${spot.id}|${playerId}|${slot}`);
  const odds = spotOdds(spot);
  for (const f of Object.keys(odds) as Find[]) {
    if ((r -= odds[f]) < 0) return f;
  }
  return "fight";
}
